version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - skeshari12
  assignees:
  - skeshari12
  versioning-strategy: increase-if-necessary
  allow:
  - dependency-type: direct
  - dependency-type: indirect
